import { Author } from '@/types';

export const ALL_AUTHORS: Author[] = [
  {
    id: 'author-1',
    name: 'Eleanor Vance',
    slug: 'eleanor-vance',
    title: 'Author & Novelist',
    initials: 'EV',
    color: 'bg-rose-100 text-rose-800 border-rose-200',
    avatar: '',
    genres: ['Fiction', 'Mystery'],
    booksPublished: 3,
    bookCount: 3,
    authorSince: '2024',
    joinDate: '2024-02-15',
    isFeatured: true,
    bio: 'Bestselling author of suspenseful psychological thrillers and atmospheric mystery novels.',
    shortBio: 'Bestselling author of psychological thrillers with Page Craft.',
    longBio: `Eleanor Vance has spent over a decade crafting intricate, suspenseful psychological thrillers that have captivated readers worldwide. Drawing inspiration from classical gothic literature and modern noir, her works explore memory, identity, and the shadows of human nature. Having published multiple acclaimed bestsellers through Page Craft, Eleanor continues to push the boundaries of narrative suspense with every release. She resides in Edinburgh with her rescue greyhound and an ever-expanding library of antique manuscripts.`,
    social: {
      twitter: 'https://twitter.com/eleanorvance_author',
      instagram: 'https://instagram.com/eleanorvance.writes',
      goodreads: 'https://goodreads.com/author/eleanor-vance',
      website: 'https://eleanorvancebooks.com',
    },
    books: [
      {
        id: 'book-ev-1',
        title: 'The Silent Echo',
        slug: 'the-silent-echo',
        category: 'Mystery',
        genre: ['Mystery', 'Psychological Thriller'],
        description: 'A secluded manor in the Scottish Highlands holds the key to a twenty-year-old disappearance that refuses to remain buried.',
        color: 'bg-rose-50 border-rose-200 text-rose-900',
        price: 399,
        format: 'Paperback & eBook',
        publishDate: 'October 2024',
        pages: 384,
        isbn: '978-93-88214-01-2',
      },
      {
        id: 'book-ev-2',
        title: 'Whispers in the Mist',
        slug: 'whispers-in-the-mist',
        category: 'Fiction',
        genre: ['Fiction', 'Suspense'],
        description: 'When an archaeologist unearths a forgotten Roman crypt beneath northern moors, secrets best left undisturbed begin to surface.',
        color: 'bg-stone-50 border-stone-200 text-stone-900',
        price: 349,
        format: 'Hardcover & eBook',
        publishDate: 'June 2025',
        pages: 320,
        isbn: '978-93-88214-02-9',
      },
      {
        id: 'book-ev-3',
        title: 'Shadows of Autumn',
        slug: 'shadows-of-autumn',
        category: 'Mystery',
        genre: ['Mystery', 'Crime Noir'],
        description: 'A retired investigator is drawn back for one last case when an enigmatic painter leaves clues encoded in her final landscape exhibition.',
        color: 'bg-amber-50 border-amber-200 text-amber-900',
        price: 449,
        format: 'Paperback & Audio',
        publishDate: 'January 2026',
        pages: 412,
        isbn: '978-93-88214-03-6',
      },
    ],
  },
  {
    id: 'author-2',
    name: 'Marcus Sterling',
    slug: 'marcus-sterling',
    title: 'Business Author & Entrepreneur',
    initials: 'MS',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
    avatar: '',
    genres: ['Business', 'Non-Fiction'],
    booksPublished: 5,
    bookCount: 5,
    authorSince: '2023',
    joinDate: '2023-08-10',
    isFeatured: true,
    bio: 'Entrepreneur, venture investor, and author sharing actionable frameworks on building enduring modern startups.',
    shortBio: 'Startup strategist and venture advisor breaking down 0-to-1 execution.',
    longBio: `Marcus Sterling is a serial technology founder, early-stage venture partner, and executive educator who has advised over fifty high-growth startups globally. His writing strips away corporate jargon to deliver battle-tested frameworks on fundraising, operational resilience, and ethical leadership. Marcus frequently speaks at international innovation summits and mentors first-time founders navigating pre-seed through Series B milestones.`,
    social: {
      twitter: 'https://twitter.com/msterling_biz',
      linkedin: 'https://linkedin.com/in/marcussterling',
      website: 'https://marcussterling.io',
    },
    books: [
      {
        id: 'book-ms-1',
        title: 'Startup Playbook: From Zero to Scale',
        slug: 'startup-playbook',
        category: 'Business',
        genre: ['Business', 'Entrepreneurship'],
        description: 'The definitive blueprint for taking ideas from napkin sketches to sustainable, multi-million dollar revenue engines.',
        color: 'bg-blue-50 border-blue-200 text-blue-900',
        price: 599,
        format: 'Paperback & eBook',
        publishDate: 'November 2023',
        pages: 296,
        isbn: '978-93-88214-10-4',
      },
      {
        id: 'book-ms-2',
        title: 'Scaling Beyond Zero',
        slug: 'scaling-beyond-zero',
        category: 'Non-Fiction',
        genre: ['Non-Fiction', 'Management'],
        description: 'How modern leaders maintain culture, speed, and focus as their headcounts expand across global distributed teams.',
        color: 'bg-sky-50 border-sky-200 text-sky-900',
        price: 499,
        format: 'Hardcover & Audio',
        publishDate: 'May 2024',
        pages: 340,
        isbn: '978-93-88214-11-1',
      },
      {
        id: 'book-ms-3',
        title: 'The Strategic Founder',
        slug: 'the-strategic-founder',
        category: 'Business',
        genre: ['Business', 'Strategy'],
        description: 'Decision-making models for navigating uncertainty, competitor threats, and rapid technological disruption.',
        color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        price: 449,
        format: 'Paperback',
        publishDate: 'February 2025',
        pages: 272,
        isbn: '978-93-88214-12-8',
      },
    ],
  },
  {
    id: 'author-3',
    name: 'Sarah Jenkins',
    slug: 'sarah-jenkins',
    title: 'Romance Writer',
    initials: 'SJ',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    avatar: '',
    genres: ['Romance', 'Fiction'],
    booksPublished: 2,
    bookCount: 2,
    authorSince: '2024',
    joinDate: '2024-05-18',
    isFeatured: true,
    bio: 'Writing heartwarming contemporary romance set in scenic coastal towns and close-knit communities.',
    shortBio: 'Contemporary romance writer celebrating hope, warmth, and second chances.',
    longBio: `Sarah Jenkins writes poignant, character-driven romance novels celebrated for their emotional depth, scenic charm, and authentic relationship journeys. Drawing from her life in a coastal village, Sarah weaves rich tapestries of found family, healing, and heartfelt romance that stay with readers long after the final chapter is turned.`,
    social: {
      instagram: 'https://instagram.com/sarahjenkins_author',
      goodreads: 'https://goodreads.com/author/sarah-jenkins',
      facebook: 'https://facebook.com/sarahjenkinsbooks',
    },
    books: [
      {
        id: 'book-sj-1',
        title: 'Whispers of Time',
        slug: 'whispers-of-time',
        category: 'Romance',
        genre: ['Romance', 'Contemporary Fiction'],
        description: 'An architectural restorer returns to her seaside hometown to renovate a Victorian lighthouse, only to confront old letters and unresolved love.',
        color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        price: 299,
        format: 'Paperback & eBook',
        publishDate: 'August 2024',
        pages: 310,
        isbn: '978-93-88214-20-3',
      },
      {
        id: 'book-sj-2',
        title: 'Summer at Willow Creek',
        slug: 'summer-at-willow-creek',
        category: 'Romance',
        genre: ['Romance', 'Small Town'],
        description: 'Two rival café owners find themselves paired together to save the annual heritage festival, discovering sparks in the process.',
        color: 'bg-teal-50 border-teal-200 text-teal-900',
        price: 329,
        format: 'Paperback',
        publishDate: 'June 2025',
        pages: 288,
        isbn: '978-93-88214-21-0',
      },
    ],
  },
  {
    id: 'author-4',
    name: 'David Chen',
    slug: 'david-chen',
    title: 'Science Fiction Author',
    initials: 'DC',
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    avatar: '',
    genres: ['Sci-Fi', 'Fantasy'],
    booksPublished: 4,
    bookCount: 4,
    authorSince: '2023',
    joinDate: '2023-11-04',
    isFeatured: true,
    bio: 'Exploring the intersection of artificial intelligence, planetary exploration, and the human spirit in near-future settings.',
    shortBio: 'Hard sci-fi novelist and computational researcher.',
    longBio: `David Chen combines his background in computer engineering with a lifelong love of speculative fiction. His hard science-fiction sagas explore what it means to be human in an era of technological singularities, quantum computing, and cosmic exploration. He has been praised by critics for blending rigorous scientific realism with deeply resonant philosophical questions.`,
    social: {
      twitter: 'https://twitter.com/davidchen_scifi',
      website: 'https://davidchennovels.com',
      linkedin: 'https://linkedin.com/in/davidchen-author',
    },
    books: [
      {
        id: 'book-dc-1',
        title: 'Digital Frontiers',
        slug: 'digital-frontiers',
        category: 'Sci-Fi',
        genre: ['Sci-Fi', 'Cyberpunk'],
        description: 'In a neon-drenched Singapore of 2088, an ethical hacker discovers that the digital afterlife network is developing a collective consciousness.',
        color: 'bg-purple-50 border-purple-200 text-purple-900',
        price: 499,
        format: 'Paperback & eBook',
        publishDate: 'December 2023',
        pages: 420,
        isbn: '978-93-88214-30-2',
      },
      {
        id: 'book-dc-2',
        title: 'Echoes of Eternity',
        slug: 'echoes-of-eternity',
        category: 'Sci-Fi',
        genre: ['Sci-Fi', 'Space Opera'],
        description: 'A deep-space relay crew receives an acoustic transmission from the edge of the Kuiper belt that predates human civilization by millennia.',
        color: 'bg-violet-50 border-violet-200 text-violet-900',
        price: 399,
        format: 'Hardcover & eBook',
        publishDate: 'September 2024',
        pages: 368,
        isbn: '978-93-88214-31-9',
      },
    ],
  },
  {
    id: 'author-5',
    name: 'Elena Rodriguez',
    slug: 'elena-rodriguez',
    title: 'Culinary Author & Memoirist',
    initials: 'ER',
    color: 'bg-amber-100 text-amber-800 border-amber-200',
    avatar: '',
    genres: ['Memoir', 'Non-Fiction'],
    booksPublished: 2,
    bookCount: 2,
    authorSince: '2024',
    joinDate: '2024-03-22',
    bio: 'Award-winning chef documenting her gastronomic adventures, family recipes, and memories across southern Europe.',
    shortBio: 'Chef and culinary memoirist capturing taste and heritage.',
    longBio: `Elena Rodriguez is a Michelin-trained chef and culinary historian whose memoirs weave food, travel, and personal resilience. Her writing transports readers to sun-drenched Andalusian olive groves and bustling Mediterranean markets, celebrating the communal power of the dinner table.`,
    social: {
      instagram: 'https://instagram.com/elena_cooks_words',
      website: 'https://elenarodriguezcuisine.com',
    },
    books: [
      {
        id: 'book-er-1',
        title: 'Culinary Magic: Flavors of Andalusia',
        slug: 'culinary-magic',
        category: 'Memoir',
        genre: ['Memoir', 'Cookbook'],
        description: 'Part memoir, part culinary homage — eighty authentic heirloom recipes intertwined with stories of three generations of Spanish women.',
        color: 'bg-amber-50 border-amber-200 text-amber-900',
        price: 549,
        format: 'Hardcover Full-Color',
        publishDate: 'May 2024',
        pages: 280,
        isbn: '978-93-88214-40-1',
      },
    ],
  },
  {
    id: 'author-6',
    name: 'Amanda Clarke',
    slug: 'amanda-clarke',
    title: "Children's Author & Illustrator",
    initials: 'AC',
    color: 'bg-orange-100 text-orange-800 border-orange-200',
    avatar: '',
    genres: ['Children', 'Fiction'],
    booksPublished: 6,
    bookCount: 6,
    authorSince: '2023',
    joinDate: '2023-04-12',
    bio: 'Creator of the beloved "Little Paws" illustrated series fostering imagination, kindness, and wonder in young readers.',
    shortBio: 'Children’s storybook creator and visual artist.',
    longBio: `Amanda Clarke is an award-winning children's author and illustrator whose charming picture books have delighted early readers and parents worldwide. Her storytelling champions empathy, curiosity, and environmental mindfulness through vibrant, expressive animal characters.`,
    social: {
      instagram: 'https://instagram.com/amandaclarke_art',
      twitter: 'https://twitter.com/amandaclarkekids',
    },
    books: [
      {
        id: 'book-ac-1',
        title: 'The Little Paws Adventure',
        slug: 'the-little-paws-adventure',
        category: 'Children',
        genre: ['Children', 'Picture Book'],
        description: 'Join Barnaby the bear and his woodland friends as they learn the power of teamwork during the Great Pine Festival.',
        color: 'bg-orange-50 border-orange-200 text-orange-900',
        price: 299,
        format: 'Hardcover Picture Book',
        publishDate: 'July 2023',
        pages: 48,
        isbn: '978-93-88214-50-0',
      },
    ],
  },
  {
    id: 'author-7',
    name: 'Dr. Robert Hale',
    slug: 'dr-robert-hale',
    title: 'Economics Professor & Analyst',
    initials: 'RH',
    color: 'bg-teal-100 text-teal-800 border-teal-200',
    avatar: '',
    genres: ['Non-Fiction', 'Business'],
    booksPublished: 3,
    bookCount: 3,
    authorSince: '2023',
    joinDate: '2023-09-01',
    bio: 'Distinguished academic and researcher translating complex macro-market dynamics into accessible economic analysis.',
    shortBio: 'Economist demystifying modern financial systems.',
    longBio: `Dr. Robert Hale holds a chair in Applied Macroeconomics and has served as a consultant to multinational policy institutions. His books bridge the gap between academic theory and everyday economic reality, empowering readers to understand inflation, monetary policy, and global wealth distribution.`,
    social: {
      linkedin: 'https://linkedin.com/in/drroberthale',
      twitter: 'https://twitter.com/drroberthale',
    },
    books: [
      {
        id: 'book-rh-1',
        title: 'Modern Economics Explained',
        slug: 'modern-economics-explained',
        category: 'Non-Fiction',
        genre: ['Non-Fiction', 'Economics'],
        description: 'A clear, lucid guide through supply shocks, central bank balance sheets, and the shifting geopolitical trade landscape.',
        color: 'bg-teal-50 border-teal-200 text-teal-900',
        price: 499,
        format: 'Paperback & eBook',
        publishDate: 'January 2024',
        pages: 350,
        isbn: '978-93-88214-60-9',
      },
    ],
  },
  {
    id: 'author-8',
    name: 'Jessica Wong',
    slug: 'jessica-wong',
    title: 'Epic Fantasy Novelist',
    initials: 'JW',
    color: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    avatar: '',
    genres: ['Fantasy', 'Sci-Fi'],
    booksPublished: 3,
    bookCount: 3,
    authorSince: '2024',
    joinDate: '2024-01-19',
    bio: 'World-builder crafting sweeping high-fantasy sagas rich with ancient folklore, intricate magic systems, and legendary dynasties.',
    shortBio: 'High-fantasy worldbuilder and mythology enthusiast.',
    longBio: `Jessica Wong crafts expansive fantasy worlds layered with rich cultural tapestries, complex political intrigue, and unforgettable ensemble casts. Her novels have garnered passionate fan followings for their lush prose and thrilling magical combat.`,
    social: {
      instagram: 'https://instagram.com/jessicawong_fantasy',
      twitter: 'https://twitter.com/jessicawong_pen',
    },
    books: [
      {
        id: 'book-jw-1',
        title: 'Chronicles of the Sunken Isles',
        slug: 'chronicles-of-the-sunken-isles',
        category: 'Fantasy',
        genre: ['Fantasy', 'Epic Fantasy'],
        description: 'When ancient oceanic wards crack open, an exiled cartographer must ally with sea-sorcerers to chart a forgotten realm.',
        color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        price: 449,
        format: 'Hardcover & eBook',
        publishDate: 'April 2024',
        pages: 512,
        isbn: '978-93-88214-70-8',
      },
    ],
  },
  {
    id: 'author-9',
    name: 'Tom Baker',
    slug: 'tom-baker',
    title: 'Crime & Mystery Novelist',
    initials: 'TB',
    color: 'bg-red-100 text-red-800 border-red-200',
    avatar: '',
    genres: ['Mystery', 'Fiction'],
    booksPublished: 8,
    bookCount: 8,
    authorSince: '2023',
    joinDate: '2023-01-14',
    bio: 'Veteran investigative detective turned bestselling crime novelist, acclaimed for relentless pacing and gritty authenticity.',
    shortBio: 'Former investigator turning real procedural grit into gripping crime fiction.',
    longBio: `Tom Baker spent twenty-two years with metropolitan investigative bureaus before dedicating his life to writing gritty, uncompromising detective fiction. His novels are renowned for their razor-sharp procedural accuracy and deeply authentic portrayals of urban crime investigations.`,
    social: {
      twitter: 'https://twitter.com/tombaker_noir',
      facebook: 'https://facebook.com/tombakercrime',
    },
    books: [
      {
        id: 'book-tb-1',
        title: 'Urban Legends',
        slug: 'urban-legends',
        category: 'Mystery',
        genre: ['Mystery', 'Crime'],
        description: 'A string of staged crime scenes in London’s docklands mirrors famous 19th-century folklore tales, baffling Scotland Yard.',
        color: 'bg-red-50 border-red-200 text-red-900',
        price: 329,
        format: 'Paperback & Audio',
        publishDate: 'March 2023',
        pages: 360,
        isbn: '978-93-88214-80-7',
      },
    ],
  },
  {
    id: 'author-10',
    name: 'Rachel Greene',
    slug: 'rachel-greene',
    title: 'Contemporary Fiction Writer',
    initials: 'RG',
    color: 'bg-pink-100 text-pink-800 border-pink-200',
    avatar: '',
    genres: ['Romance', 'Fiction'],
    booksPublished: 4,
    bookCount: 4,
    authorSince: '2024',
    joinDate: '2024-04-02',
    bio: 'Crafting emotionally poignant narratives about family ties, personal transformation, and finding beauty in the everyday.',
    shortBio: 'Novelist exploring modern womanhood and personal healing.',
    longBio: `Rachel Greene’s novels celebrate resilience, friendship, and the quiet epiphanies of everyday life. With an empathetic voice and sharp psychological insight, Rachel writes stories that resonate with book clubs and fiction enthusiasts across the country.`,
    social: {
      instagram: 'https://instagram.com/rachelgreene_writes',
      goodreads: 'https://goodreads.com/author/rachel-greene',
    },
    books: [
      {
        id: 'book-rg-1',
        title: 'Letters to Nowhere',
        slug: 'letters-to-nowhere',
        category: 'Fiction',
        genre: ['Fiction', 'Drama'],
        description: 'A woman discovers a box of unsent letters in her grandmother’s attic, embarking on a cross-country journey of family reconciliation.',
        color: 'bg-pink-50 border-pink-200 text-pink-900',
        price: 349,
        format: 'Paperback & eBook',
        publishDate: 'July 2024',
        pages: 304,
        isbn: '978-93-88214-90-6',
      },
    ],
  },
  {
    id: 'author-11',
    name: "Michael O'Connor",
    slug: 'michael-oconnor',
    title: 'Historical Fiction Novelist',
    initials: 'MO',
    color: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    avatar: '',
    genres: ['Fiction', 'Mystery'],
    booksPublished: 2,
    bookCount: 2,
    authorSince: '2024',
    joinDate: '2024-06-10',
    bio: 'Irish historical author acclaimed for immersive period prose and nuanced storytelling of forgotten historical moments.',
    shortBio: 'Historical novelist bringing 20th-century history to vivid life.',
    longBio: `Michael O'Connor is an Irish author and historian whose evocative period novels bring forgotten corners of 20th-century history to vivid life. His works have been praised for their lyricism and meticulous archival authenticity.`,
    social: {
      twitter: 'https://twitter.com/moconnor_author',
      website: 'https://michaeloconnorbooks.ie',
    },
    books: [
      {
        id: 'book-mo-1',
        title: 'The Kerry Coast',
        slug: 'the-kerry-coast',
        category: 'Fiction',
        genre: ['Historical Fiction', 'Drama'],
        description: 'Set during the turbulent winter of 1922, a coastal lighthouse keeper struggles to remain neutral as revolution sweeps the countryside.',
        color: 'bg-cyan-50 border-cyan-200 text-cyan-900',
        price: 399,
        format: 'Paperback & Hardcover',
        publishDate: 'August 2024',
        pages: 336,
        isbn: '978-93-88214-91-3',
      },
    ],
  },
  {
    id: 'author-12',
    name: 'Sophie Turner',
    slug: 'sophie-turner',
    title: 'Botanist & Nature Essayist',
    initials: 'ST',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    avatar: '',
    genres: ['Non-Fiction', 'Memoir'],
    booksPublished: 2,
    bookCount: 2,
    authorSince: '2024',
    joinDate: '2024-07-05',
    bio: 'Ecologist exploring the surprising vitality of native plants in modern metropolitan landscapes.',
    shortBio: 'Botanist and nature writer revealing urban green wonder.',
    longBio: `Sophie Turner is a field botanist and environmental essayist who has spent years documenting how wild flora reclaims urban spaces. Her poetic, observant prose encourages readers to find connection with the natural world right at their doorsteps.`,
    social: {
      instagram: 'https://instagram.com/sophieturner_flora',
      website: 'https://sophieturnerbotany.org',
    },
    books: [
      {
        id: 'book-st-1',
        title: 'The Secret Life of Urban Flora',
        slug: 'the-secret-life-of-urban-flora',
        category: 'Non-Fiction',
        genre: ['Nature', 'Essays'],
        description: 'An enchanting exploration of the wildflowers, mosses, and ancient trees thriving in cracks of concrete across mega-cities.',
        color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        price: 379,
        format: 'Hardcover Illustrated',
        publishDate: 'September 2024',
        pages: 240,
        isbn: '978-93-88214-92-0',
      },
    ],
  },
  {
    id: 'author-13',
    name: 'James Wilson',
    slug: 'james-wilson',
    title: 'Leadership & Innovation Author',
    initials: 'JW',
    color: 'bg-slate-100 text-slate-800 border-slate-200',
    avatar: '',
    genres: ['Business', 'Non-Fiction'],
    booksPublished: 3,
    bookCount: 3,
    authorSince: '2023',
    joinDate: '2023-06-20',
    bio: 'Executive coach and innovation strategist guiding global leaders through organizational transformation.',
    shortBio: 'Organizational advisor writing on agile leadership.',
    longBio: `James Wilson has coached executive teams across Fortune 500 enterprises on innovation agility, trust-building, and high-performance collaboration. His writing translates complex team dynamics into clear, empowering habits.`,
    social: {
      linkedin: 'https://linkedin.com/in/jameswilson-leadership',
      twitter: 'https://twitter.com/jwilson_lead',
    },
    books: [
      {
        id: 'book-jwils-1',
        title: 'Beyond the Horizon',
        slug: 'beyond-the-horizon',
        category: 'Business',
        genre: ['Leadership', 'Management'],
        description: 'How modern enterprises stay ahead of existential technology curves by building decentralized innovation engines.',
        color: 'bg-slate-50 border-slate-200 text-slate-900',
        price: 349,
        format: 'Paperback & eBook',
        publishDate: 'October 2023',
        pages: 310,
        isbn: '978-93-88214-93-7',
      },
    ],
  },
  {
    id: 'author-14',
    name: 'Lily Evans',
    slug: 'lily-evans',
    title: 'YA Fantasy & Mythology Writer',
    initials: 'LE',
    color: 'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
    avatar: '',
    genres: ['Fantasy', 'Children'],
    booksPublished: 2,
    bookCount: 2,
    authorSince: '2024',
    joinDate: '2024-03-01',
    bio: 'Weaving rich coming-of-age tales rooted in ancient Celtic and Norse mythology for young adults worldwide.',
    shortBio: 'YA fantasy writer bringing ancient lore to modern youth.',
    longBio: `Lily Evans is a young adult fantasy novelist who weaves ancient folklore into high-stakes adventures of courage, identity, and magic. Her storytelling has been celebrated for its lush atmosphere and unforgettable protagonists.`,
    social: {
      instagram: 'https://instagram.com/lilyevans_magic',
      twitter: 'https://twitter.com/lilyevans_ya',
    },
    books: [
      {
        id: 'book-le-1',
        title: 'Weavers of Starlight',
        slug: 'weavers-of-starlight',
        category: 'Fantasy',
        genre: ['YA Fantasy', 'Mythology'],
        description: 'A young weaver discovers that the tapestry she creates each night alters the constellations and fate of the mortal world.',
        color: 'bg-fuchsia-50 border-fuchsia-200 text-fuchsia-900',
        price: 399,
        format: 'Paperback & Audio',
        publishDate: 'May 2024',
        pages: 360,
        isbn: '978-93-88214-94-4',
      },
    ],
  },
];

export const ALL_GENRES = [
  'All',
  'Fiction',
  'Non-Fiction',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Fantasy',
  'Business',
  'Memoir',
  'Children',
];

export function getAllAuthors(): Author[] {
  return ALL_AUTHORS;
}

export function getAuthorBySlug(slug: string): Author | undefined {
  const normalizedSlug = slug.toLowerCase().trim();
  return ALL_AUTHORS.find(
    (a) =>
      a.slug.toLowerCase() === normalizedSlug ||
      a.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') === normalizedSlug
  );
}

export function getAuthorsByGenre(genre: string): Author[] {
  if (!genre || genre === 'All') return ALL_AUTHORS;
  return ALL_AUTHORS.filter((author) => author.genres.includes(genre));
}

export function searchAuthors(query: string, genre: string = 'All'): Author[] {
  const trimmed = query.toLowerCase().trim();
  return ALL_AUTHORS.filter((author) => {
    const matchesSearch =
      !trimmed ||
      author.name.toLowerCase().includes(trimmed) ||
      (author.title && author.title.toLowerCase().includes(trimmed)) ||
      author.bio.toLowerCase().includes(trimmed) ||
      (author.longBio && author.longBio.toLowerCase().includes(trimmed)) ||
      author.genres.some((g) => g.toLowerCase().includes(trimmed));

    const matchesGenre = genre === 'All' || author.genres.includes(genre);

    return matchesSearch && matchesGenre;
  });
}
